### ISSUE TITLE
B encoding is not being generated properly

### ISSUE THREAD

**Issue by Boaztheostrich** [Coledunsby/CDCodabarView#8]
I am trying to make an IOS app that generates codabar barcodes to replace physical student ID's. It seems to work perfectly on ID's starting and ending with A, but for those ending with B it is generating incorrectly.

**Comment by Boaztheostrich** [comment]
It appears as if the B character is being generated as a C character: 1010010011, instead of 1001001011

**Comment by Boaztheostrich** [comment]
It looks like the "Update CDCodabarEncoder.swift" done by tonosak never got updated to the pods install method. I was able to edit it manually by changing the CDCodabarEncoder.swift file.

Just copying the changes made by tonosak seen here: https://github.com/Coledunsby/CDCodabarView/pull/7/commits/429f1bd3454eec2e72206b2096c9b85a8a554b60

**Comment by Coledunsby** [comment]
Ah, yeah I forgot to make a new release after that PR got merged. I'll make one shortly.

**Comment by Boaztheostrich** [comment]
Sounds good thank you!!

**Comment by Boaztheostrich** [comment]
Another thing to look at is making it easier for people to add the package
to their project, I know there’s a way to basically just paste the GitHub
link into code under packages and it adds it. But it threw errors for
yours.

I also had some sandbox errors and a launch screen error after installing
your package through pods that may be related to the pods method. I can
walk you through how i fixed those if you’re interested. It may have been a
coincidence tho.

**Comment by Coledunsby** [comment]
Sorry for the delay, [1.3.0](https://github.com/Coledunsby/CDCodabarView/releases/tag/1.3.0) adds Swift Package Manager support.

**Comment by Boaztheostrich** [comment]
Sounds good thank you!
